# Імпорт NumPy

In [ ]:
import numpy as np

# Основи

## Створення масиву

* За допомогою функції `array` можна створити масив.
* Масиви в NumPy мають свій тип даних - `ndarray`.
* По дефолту, тип елементів масиву - `'int64'`, але його можна змінити за допомогою атрибуту `dtype`

В даному прикладі буде створено одновимірний (1D) масив

In [ ]:
a = np.array([1, 2, 3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

Отримати розмірність масиву можна за допомогою атрибуту `ndim`

In [ ]:

a.ndim

1

Можна створювати і двовимірні (2D) масиви

In [ ]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

## Форма масиву

Кожен масив має свою форму (`shape`). Вона вказує на розмірність та кількість осей.

Розмірність масиву дорівнює кількості осей.

В даному випадку форма = (2, 3) або ж 2 рядки та 3 стовпці

In [ ]:
b.shape

(2, 3)

## Типи даних та розмір масивів

Подивитись тип даних елементів масиву можна за допомогою атрибуту `dtype`

In [ ]:
a.dtype

dtype('int32')

Розмір кожного елементу масиву в байтах можна перевірити за допомогою атрибуру `itemsize`.

В даному випадку це $4$, адже коже елемент масиву має тип даних `int32`, тобто займає $32$ біти. Один байт - це $8$ бітів. $32/8 = 4$ байти

In [ ]:
a.itemsize

4

Розмір масиву повністю можна отримати помноживши розмір кожного елементу на кількість елeментів. В даному випадку маємо $3$ елементи по $4$ байти.
$3*4 = 12$ байтів

Кількість елементів можна знайти за допомогою атрибуту `size`.

Також можна просто використати атрибут `nbytes`

In [ ]:
a.size * a.itemsize # те саме, що і a.nbytes

12

Розмір елементів масиву `b` буде більший, оскільки його елементи мають тип `float64`

In [ ]:
b.itemsize

8

# Доступ до елементів масиву

Індексування `ndarray` відбувається так само, як і в python.

Для початку створимо новий двовимірний масив

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Перевіримо його форму. Він має $2$ рядки та $7$ колонок

In [ ]:
a.shape

(2, 7)

Отримати доступ до специфічного елементу можна за допомогою індексування, надавши номер бажаного ряжка та колонки у формі `[рядок, колонка]`.

**Варто зазначити**, що індекси починаються з $0$.

Припустимо, ми хочемо отримати доступ до числа $13$. Воно знаходиться в другому рядку (індекс $1$), шостій колонкці (індекс $5$ або $-2$)

In [ ]:
a[1, 5] # те саме, що і a[1, -2]

13

Якщо ми хочемо отримати доступ до всього рядка повністю, тобто отримати всі колонки, можна використати оператор `:` на місці індекса для колонок.

Припустимо, хочемо отримати доступ до першого (індекс $0$) рядка

In [ ]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

Якщо ми хочемо отримати доступ до колонки повністю, тобто отримати всі рядки цієї колонки, можна використати оператор `:` на місці індекса для рядків.

Припустимо, хочемо отримати доступ до третьої (індекс $2$) колонки

In [ ]:
a[:, 2]

array([ 3, 10])

Можна також використовувати стандартне індексування з python.
Припустимо, ми хочемо отримати всі елементи, починаючи з `початкового_індекса`, закінчуючи `кінцевим_індексом` та з деяким `кроком` (пропускаючи по декілька елементів).

Можна використати наступне індексування:
`[початковий_індекс:кінцевий_індекс:крок]`

**Варто зазначити**, що індексування є виключним. Тобто, якщо `кінцевий_індекс` дорівнює $5$, то останнім поверне елемент з індексом $4$ ($5-1$).

Припустимо, треба отримати доступ до першого рядка, колонки з $1$ по $5$, з кроком $2$ (пропускаючи по $1$ елементу)

In [ ]:
a[0, 1:6:2] # те саме, що і a[0, 1:-1:2]

array([2, 4, 6])

# Зміна елементів масиву

In [ ]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
a[:, 2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [ ]:
a[:, 2] = [1, 2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

3-D example

In [ ]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b.shape

(2, 2, 2)

In [ ]:
# Get a specific element (work outside in)
b[0, 1, 1]

4

In [ ]:
# replace
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing different types of arrays

In [ ]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4) # np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# random decimal numbers
np.random.rand(4, 2)

array([[0.87124689, 0.25430255],
       [0.16631521, 0.68186281],
       [0.74175271, 0.88918304],
       [0.36032364, 0.49193301]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.92780761, 0.41907983, 0.76220156, 0.00717828, 0.81654016,
        0.53561212, 0.26402675],
       [0.3267872 , 0.44135362, 0.49380854, 0.46592715, 0.46544364,
        0.46034909, 0.76613521]])

In [ ]:
# Random integer values
np.random.randint(4, 7, size=(3, 3))

array([[6, 5, 6],
       [5, 6, 4],
       [6, 4, 5]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
matrix = np.ones((5, 5), dtype='int32')
matrix[1:-1, 1:-1] = 0
matrix[2, 2] = 9
matrix

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

**Be careful when copying arrays!!**

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
a, b

(array([1, 2, 3]), array([100,   2,   3]))

# Mathematics

In [ ]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a += 2
a

array([3, 4, 5, 6])

In [ ]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])

In [ ]:
a ** 2

array([ 9, 16, 25, 36])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# Linear algebra

In [ ]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In order to multiply two matrixes, the number of columns of the first matrix has to be equal to the number of rows of the second one.

In [ ]:
# Matrix multiplying
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# Matrix multiplying
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [ ]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
before.shape

(2, 4)

In [ ]:
after = before.reshape(2, 2, 2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

h3 = np.hstack((h1, h2))
h1, h2, h3

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.]]),
 array([[1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0., 0.]]))

In [ ]:
h3.shape

(2, 6)

# Miscellaneous

## Load data from file

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data.txt to data.txt


In [ ]:
filedata = np.genfromtxt('data.txt',  dtype='int32', delimiter=',')
# filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

## Boolean masking and advanved indexing

In [ ]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [ ]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
mat = np.arange(1, 31)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
mat = mat.reshape(6, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
mat[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [ ]:
mat[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [ ]:
mat[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])